services:
  server:
    env_file:
      - path: ./.env
    build: .
    ports:
      - 8080:8080
  
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - redis-data:/data
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf

volumes:
  redis-data: